import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Loto = localFont({
  src: [
    {
      path: "../assests/fonts/Lato/Lato-Light.ttf",
      weight: "300",
      style: "light",
    },
    {
      path: "../assests/fonts/Lato/Lato-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assests/fonts/Lato/Lato-Bold.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "../assests/fonts/Lato/Lato-Black.ttf",
      weight: "900",
      style: "black",
    },
  ],
  variable: "--font-lato",
  display: "swap",
});

const RedHatDisplay = localFont({
  src: [
    // { path: '../assests/fonts/RedHatDisplay/RedHatDisplay-Normal.ttf', weight: '400', style: 'normal' },
     {
      path: "../assests/fonts/RedHatDisplay/RedHatDisplay-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assests/fonts/RedHatDisplay/RedHatDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assests/fonts/RedHatDisplay/RedHatDisplay-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assests/fonts/RedHatDisplay/RedHatDisplay-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assests/fonts/RedHatDisplay/RedHatDisplay-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assests/fonts/RedHatDisplay/RedHatDisplay-Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-redhatdisplay",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`    ${Loto.variable}  ${RedHatDisplay.variable} 
     

         antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
